name: Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.19.6
      uses: actions/setup-node@v4
      with:
        node-version: 20.19.6
    - name: Install dependencies
      run: npm install --legacy-peer-deps
    - name: Test
      run: npm test -- --watch=false --browsers=ChromeHeadless
